{"errorMessage": "'Router' object is not callable", "errorType": "TypeError", "requestId": "ac347f14-6d78-42db-852a-07c923db67b0", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 50, in lambda_handler\n    return router(event, context)  # Corrected the method call here\n"]}
